## Process this file with automake to produce Makefile.in 

noinst_LIBRARIES = librenderother.a


librenderother_a_SOURCES =                                                   \
  ChaseCam.cpp                                                               \
  ChaseCam.h                                                                 \
  fades.cpp                                                                  \
  visual_effects.hpp                                                                    \
  game_window.cpp                                                            \
  hud_manager.h                                                              \
  ImageBlitter.cpp                                                           \
  ImageBlitter.h                                                             \
  images.cpp                                                                 \
  images.h                                                                   \
  motion_sensor.cpp                                                          \
  motion_sensor.h                                                            \
  automap.cpp                                                           \
  automap_data.hpp                                                             \
  OverheadMap_OGL.cpp                                                        \
  Canvas_OGL.hpp                                                          \
  AutomapRenderer.cpp                                                    \
  AutomapRenderer.h                                                      \
  screen_drawing.cpp                                                         \
  screen_drawing.h                                                           \
  screen_overlay.h                                                            \
  Screen.cpp                                                                 \
  Screen.hpp                                                                   \
  Font.cpp                                                              \
  Font.hpp                                                                \
  sdl_resize.cpp                                                             \
  sdl_resize.h                                                               \
  ShapeBlitter.cpp                                                          \
  ShapeBlitter.h                                                            \
  TextLayoutHelper.cpp                                                       \
  TextLayoutHelper.h                                                         \
  string_resources.cpp                                                       \
  string_resources.hpp                                                       \
  camera.cpp                                                            \
  camera.hpp


AM_CPPFLAGS =                                                                \
  -I$(top_srcdir)/Source_Files/CSeries                                       \
  -I$(top_srcdir)/Source_Files/Files                                         \
  -I$(top_srcdir)/Source_Files/Gameworld                                     \
  -I$(top_srcdir)/Source_Files/Input                                         \
  -I$(top_srcdir)/Source_Files/Lua                                           \
  -I$(top_srcdir)/Source_Files/Misc                                          \
  -I$(top_srcdir)/Source_Files/ModelView                                     \
  -I$(top_srcdir)/Source_Files/Network                                       \
  -I$(top_srcdir)/Source_Files/Network/Metaserver                            \
  -I$(top_srcdir)/Source_Files/RenderMain                                    \
                                                                             \
  -I$(top_srcdir)/Source_Files/Sound                                         \
  -I$(top_srcdir)/Source_Files/TCPMess                                       \
  -I$(top_srcdir)/Source_Files/Terminal                                      \
  -I$(top_srcdir)/Source_Files/Videos                                        \
  -I$(top_srcdir)/Source_Files/XML                                           \
  -I$(top_srcdir)/Source_Files
