## Process this file with automake to produce Makefile.in 

noinst_LIBRARIES = libgameworld.a


libgameworld_a_SOURCES =                                                     \
  devices.cpp                                                                \
  dynamic_limits.cpp                                                         \
  dynamic_limits.h                                                           \
  editor.h                                                                   \
  effect_definitions.h                                                       \
  effects.cpp                                                                \
  effects.h                                                                  \
  ephemera.cpp                                                               \
  ephemera.h                                                                 \
  flood_map.cpp                                                              \
  flood_map.h                                                                \
  interpolated_world.cpp                                                     \
  interpolated_world.h                                                       \
  item_definitions.h                                                         \
  items.cpp                                                                  \
  items.h                                                                    \
  lightsource.cpp                                                            \
  lightsource.h                                                              \
  map_constructors.cpp                                                       \
  map.cpp                                                                    \
  map.h                                                                      \
  marathon2.cpp                                                              \
  media_definitions.h                                                        \
  media.cpp                                                                  \
  media.h                                                                    \
  monster_definitions.h                                                      \
  monsters.cpp                                                               \
  monsters.h                                                                 \
  pathfinding.cpp                                                            \
  physics_models.h                                                           \
  physics.cpp                                                                \
  placement.cpp                                                              \
  platform_definitions.h                                                     \
  platforms.cpp                                                              \
  platforms.h                                                                \
  player.cpp                                                                 \
  player.h                                                                   \
  projectile_definitions.h                                                   \
  projectiles.cpp                                                            \
  projectiles.h                                                              \
  scenery_definitions.h                                                      \
  scenery.cpp                                                                \
  scenery.h                                                                  \
  TickBasedCircularQueue.h                                                   \
  weapon_definitions.h                                                       \
  weapons.cpp                                                                \
  weapons.h                                                                  \
  world.cpp                                                                  \
  world.h


AM_CPPFLAGS =                                                                \
  -I$(top_srcdir)/Source_Files/CSeries                                       \
  -I$(top_srcdir)/Source_Files/Files                                         \
                                                                             \
  -I$(top_srcdir)/Source_Files/Input                                         \
  -I$(top_srcdir)/Source_Files/Lua                                           \
  -I$(top_srcdir)/Source_Files/Misc                                          \
  -I$(top_srcdir)/Source_Files/ModelView                                     \
  -I$(top_srcdir)/Source_Files/Network                                       \
  -I$(top_srcdir)/Source_Files/Network/Metaserver                            \
  -I$(top_srcdir)/Source_Files/RenderMain                                    \
  -I$(top_srcdir)/Source_Files/RenderOther                                   \
  -I$(top_srcdir)/Source_Files/Sound                                         \
  -I$(top_srcdir)/Source_Files/TCPMess                                       \
  -I$(top_srcdir)/Source_Files/Terminal                                      \
  -I$(top_srcdir)/Source_Files/Videos                                        \
  -I$(top_srcdir)/Source_Files/XML                                           \
  -I$(top_srcdir)/Source_Files
